// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASSDKlkj4OD7dw-pEJUs3WbNugg5fQOOs',
    appId: '1:277709952366:web:e9e1ae32a40e1bb3d4dd7f',
    messagingSenderId: '277709952366',
    projectId: 'allopark-81d0a',
    authDomain: 'allopark-81d0a.firebaseapp.com',
    storageBucket: 'allopark-81d0a.appspot.com',
    measurementId: 'G-5WT6ZFXE7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGXzBAjGSqWCXF1mv4IbY0rZ8QNNgsXG4',
    appId: '1:277709952366:android:83986faccb1b7e02d4dd7f',
    messagingSenderId: '277709952366',
    projectId: 'allopark-81d0a',
    storageBucket: 'allopark-81d0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_bUxAdF6ket1RnpWq67c1a0Ex5GAMZro',
    appId: '1:277709952366:ios:9a00179fe2789b71d4dd7f',
    messagingSenderId: '277709952366',
    projectId: 'allopark-81d0a',
    storageBucket: 'allopark-81d0a.appspot.com',
    iosClientId: '277709952366-cviv8455fb76cqkhla0mv5p3mjeh0fhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.alloPark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_bUxAdF6ket1RnpWq67c1a0Ex5GAMZro',
    appId: '1:277709952366:ios:9a00179fe2789b71d4dd7f',
    messagingSenderId: '277709952366',
    projectId: 'allopark-81d0a',
    storageBucket: 'allopark-81d0a.appspot.com',
    iosClientId: '277709952366-cviv8455fb76cqkhla0mv5p3mjeh0fhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.alloPark',
  );
}
